// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZnOpPFbjSuff1EaqSl9Diol-00UXtd-0',
    appId: '1:1004683620206:android:4d00e8240aeae3123cdb7f',
    messagingSenderId: '1004683620206',
    projectId: 'uzprojectcom',
    storageBucket: 'uzprojectcom.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxEJVP_Z0wzFW9YtD9aqPvJt94urdXsU',
    appId: '1:1004683620206:web:fb47e63d0f9a40593cdb7f',
    messagingSenderId: '1004683620206',
    projectId: 'uzprojectcom',
    authDomain: 'uzprojectcom.firebaseapp.com',
    storageBucket: 'uzprojectcom.firebasestorage.app',
    measurementId: 'G-G909K42V7F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwQ39vgw7cXhl8JL2BQ1UZKsjXsEHJmfA',
    appId: '1:1004683620206:ios:0fc106f078f3a1713cdb7f',
    messagingSenderId: '1004683620206',
    projectId: 'uzprojectcom',
    storageBucket: 'uzprojectcom.firebasestorage.app',
    iosBundleId: 'uz.uzinfocom.uchar',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQ39vgw7cXhl8JL2BQ1UZKsjXsEHJmfA',
    appId: '1:1004683620206:ios:0fc106f078f3a1713cdb7f',
    messagingSenderId: '1004683620206',
    projectId: 'uzprojectcom',
    storageBucket: 'uzprojectcom.firebasestorage.app',
    iosBundleId: 'uz.uzinfocom.uchar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvxEJVP_Z0wzFW9YtD9aqPvJt94urdXsU',
    appId: '1:1004683620206:web:4b3ff44dcab448d53cdb7f',
    messagingSenderId: '1004683620206',
    projectId: 'uzprojectcom',
    authDomain: 'uzprojectcom.firebaseapp.com',
    storageBucket: 'uzprojectcom.firebasestorage.app',
    measurementId: 'G-B8T7DD5C7Z',
  );

}